### ISSUE TITLE
Separating common framework from concrete examples/site generators

### ISSUE THREAD

**Issue by igordejanovic** [Pazzo92/products-mining#3]
All of `.rbt` files in the `dsl/language` and accompanying `.py` files are actually examples.

I suggest making a top level `examples` folder with a subfolder for each site you are generating for. 
Only a basic/common framework goes into the project package itself. 

User of the package should define:
- entity type with css mapping
- tag text transformation func in accompanying `.py` file,

In addition language should probably specify the target URL where scrapping should be performed?

Think of it as a general DSL for scrapping definition.

**Comment by Pazzo92** [comment]
Created root folder `examples` , with sub-folders representing domains (sites).
In each site folder there is a DSL example of the program and subfolder `types` holding definition of each type.
When running the project, in `generate.py` you define scraping item and the site:

```
 # DEFINE THE TYPE AND THE DOMAIN OF THE SCRAPING ITEM
    domain = "imdb"
    type = "movie"
```

**Comment by igordejanovic** [comment]
Looks good. BTW, why queries and type definitions both have `.rbt` extension? Looks like you took the extension from textX robot example :)

I suggest to have separate extension for type definition and for query. E.g. `sdt` and `sdq` (form **s**crapping **D**SL **t**ype/**q**uery.

**Comment by Pazzo92** [comment]
You are right, it is from the robot example, never did change it. :)
Good suggestion, changed.
