### ISSUE TITLE
Create setup.py

### ISSUE THREAD

**Issue by igordejanovic** [Pazzo92/products-mining#4]
Project should have a valid setup.py to be installable using setuptools and deployable to PyPI.

**Comment by Pazzo92** [comment]
Created setup.py and uploaded to PyPi.

**Comment by igordejanovic** [comment]
I suggest that top-level package/folder be named something like `scraping_dsl` instead of `dsl` as it is too generic and could easily clash with some other package when installed. Also I suggest you start with `0.1` version and development status to be 4 - beta.

You are not using Arpeggio directly, are you? If so, remove it from the dependencies. textX dependency will pull in Arpeggio.

**Comment by Pazzo92** [comment]
Changes done.
